### ISSUE TITLE
At runtime keys interrupt ArtSaver

### ISSUE THREAD

**Issue by woodenzen** [GabZach/ArtSaver#7]
> Controls at runtime (in the regular app): go back to previously shown images (cursor keys, aka. ), pause the slide show (space bar), have ArtSaver show the current image in Finder (return key), or delete the current image (delete key, can be disabled). 
> There are more controls available at runtime: for information see the Manual in the Options pane, or press H during the slide show.

This feature isn't working for me in Catalina. Works great in High Sierra.
Any! key I press stops the screensaver. H, DELETE, ARROW KEYS all stop the screensaver. I don't see the option to turn this on or off in the user settings.

**Comment by GabZach** [comment]
Thanks a lot for the hint - that is a bug on the web page.  I have corrected the web page to better reflect this limitation (I hope). 

Yes, the feature works fine under High Sierra, because in the version of macOS, Apple stills allows keyboard control for screen savers, but starting with Catalina, Apple is prohibiting that (and there is a good security reason for that). There is nothing I can do about it.

Keyboard controls dowry, however, in the regular app ArtSaverApp.

**Comment by GabZach** [comment]
starting with Catalina, Apple is prohibiting that (and there is a good security reason for that). There is nothing I can do about it.

**Comment by GabZach** [comment]
starting with Catalina, Apple is prohibiting that (and there is a good security reason for that). There is nothing I can do about it.

**Comment by GabZach** [comment]
starting with Catalina, Apple is prohibiting that (and there is a good security reason for that). There is nothing I can do about it.
